### ISSUE TITLE
Redux: Server rendering not working

### ISSUE THREAD

**Issue by AlexandreKilian** [Limenius/symfony-react-sandbox#11]
Using Redux, the Server rendering isn't working. I get the following error message

```
SERVER] Exception in rendering!(anonymous function) @ (index):55
(index):56 [SERVER] message: match needs a history or a location(anonymous function) @ (index):56
(index):57 [SERVER] stack: Invariant Violation: match needs a history or a location
    at invariant (/private/var/folders/n2/ld8jc1w55xj757fyvyc0xg4r0000gn/T/nacmartin_phpexecjs57a09385d54899.66181123.js:23465:16)
    at match (/private/var/folders/n2/ld8jc1w55xj757fyvyc0xg4r0000gn/T/nacmartin_phpexecjs57a09385d54899.66181123.js:51536:61)
    at mainNode (/private/var/folders/n2/ld8jc1w55xj757fyvyc0xg4r0000gn/T/nacmartin_phpexecjs57a09385d54899.66181123.js:21713:29)
    at createReactElement (/private/var/folders/n2/ld8jc1w55xj757fyvyc0xg4r0000gn/T/nacmartin_phpexecjs57a09385d54899.66181123.js:19305:13)
    at serverRenderReactComponent (/private/var/folders/n2/ld8jc1w55xj757fyvyc0xg4r0000gn/T/nacmartin_phpexecjs57a09385d54899.66181123.js:21556:72)
    at Object.serverRenderReactComponent (/private/var/folders/n2/ld8jc1w55xj757fyvyc0xg4r0000gn/T/nacmartin_phpexecjs57a09385d54899.66181123.js:275:54)
    at eval (eval at <anonymous> (/private/var/folders/n2/ld8jc1w55xj757fyvyc0xg4r0000gn/T/nacmartin_phpexecjs57a09385d54899.66181123.js:52426:8), <anonymous>:7:23)
    at eval (eval at <anonymous> (/private/var/folders/n2/ld8jc1w55xj757fyvyc0xg4r0000gn/T/nacmartin_phpexecjs57a09385d54899.66181123.js:52426:8), <anonymous>:14:3)
    at /private/var/folders/n2/ld8jc1w55xj757fyvyc0xg4r0000gn/T/nacmartin_phpexecjs57a09385d54899.66181123.js:52426:8
    at /private/var/folders/n2/ld8jc1w55xj757fyvyc0xg4r0000gn/T/nacmartin_phpexecjs57a09385d54899.66181123.js:52432:14
```

**Comment by AlexandreKilian** [comment]
I fixed that problem in the same pull request:
https://github.com/Limenius/symfony-react-sandbox/pull/10

You imported the location from the store but tried to use the one from the props instead

**Comment by nacmartin** [comment]
Thanks, @AlexandreKilian for the report and the PR :)
