### ISSUE TITLE
Sandbox bug

### ISSUE THREAD

**Issue by tylerm22** [Limenius/symfony-react-sandbox#18]
Getting an error on install - not sure how to fix or if it is an issue on your end.

`Exception in rendering!

Message: (0 , _reactRouter.createServerRenderContext) is not a function

TypeError: (0 , _reactRouter.createServerRenderContext) is not a function
    at exports.default (/private/var/folders/q_/ws3x7hmn32l49288mlc3ymqc0000gn/T/nacmartin_phpexecjs589553a4f354f5.13490040.js:16725:62)
    at createReactElement (/private/var/folders/q_/ws3x7hmn32l49288mlc3ymqc0000gn/T/nacmartin_phpexecjs589553a4f354f5.13490040.js:9808:12)
    at serverRenderReactComponent (/private/var/folders/q_/ws3x7hmn32l49288mlc3ymqc0000gn/T/nacmartin_phpexecjs589553a4f354f5.13490040.js:33170:71)
    at Object.serverRenderReactComponent (/private/var/folders/q_/ws3x7hmn32l49288mlc3ymqc0000gn/T/nacmartin_phpexecjs589553a4f354f5.13490040.js:14663:53)
    at eval (eval at <anonymous> (/private/var/folders/q_/ws3x7hmn32l49288mlc3ymqc0000gn/T/nacmartin_phpexecjs589553a4f354f5.13490040.js:37655:8), <anonymous>:4:23)
    at eval (eval at <anonymous> (/private/var/folders/q_/ws3x7hmn32l49288mlc3ymqc0000gn/T/nacmartin_phpexecjs589553a4f354f5.13490040.js:37655:8), <anonymous>:11:3)
    at /private/var/folders/q_/ws3x7hmn32l49288mlc3ymqc0000gn/T/nacmartin_phpexecjs589553a4f354f5.13490040.js:37655:8
    at /private/var/folders/q_/ws3x7hmn32l49288mlc3ymqc0000gn/T/nacmartin_phpexecjs589553a4f354f5.13490040.js:37661:14
    at console.history (/private/var/folders/q_/ws3x7hmn32l49288mlc3ymqc0000gn/T/nacmartin_phpexecjs589553a4f354f5.13490040.js:1:92)
    at Object.<anonymous> (/private/var/folders/q_/ws3x7hmn32l49288mlc3ymqc0000gn/T/nacmartin_phpexecjs589553a4f354f5.13490040.js:1:110)`

**Comment by nacmartin** [comment]
Uhm.. thanks for reporting this! It looks like react-router has renamed ServerRouter into StaticRouter recently ( https://github.com/ReactTraining/react-router/commit/374a6de78d38f0b0458984b6d62ab5a9b06d7e7f ). The example code needs an update. I will do it in the next few days.

**Comment by tylerm22** [comment]
Thanks, what's a quick fix I can apply now then? I am building an app off of this

**Comment by nacmartin** [comment]
Sure, I have updated the examples to reflect their changes. If for whatever reason it happens again, if instead of using npm you use yarn ( https://yarnpkg.com/ ), there is a `yarn.lock` for JS dependencies (pretty similar to what `composer.lock` does), so you can use the exact same versions that the last commit of this library used, so they should be quite ok.

In this case I thought last week that it would be a good idea to update the sandbox to use react-router v4, that is about to be released and it looks much nicer, hoping that they wouldn't break compatibility in the last betas, but clearly they had other ideas in mind. The rest of the packages used should give less surprises.

**Comment by tylerm22** [comment]
Cool thank you :)

is there anyway in the future you can add a user element to the tutorial to better show how react can basically do anything.

Thanks :)

**Comment by nacmartin** [comment]
Do you mean user login/registering/authentication features? I think that it may be too much for the sandbox, that we try to keep as simple as possible and focused on basic React/Webpack integration and not in a full exploration of all the things that can be done. The more features, the more code to maintain and check if there are better libraries for the task from time to time.

But I was pondering if it would be worthwhile to write some tutorials in a blog exploring different possibilities (in this case maybe a post about integrating https://github.com/lexik/LexikJWTAuthenticationBundle to have authentication) and this comment encourages me to find the time to do it :)

**Comment by tylerm22** [comment]
@nacmartin that'd be good. what i am trying to do is check if_granted in the react code to see if the user can add a recipe or not, but I can't figure out how. Is that needing any additional API parameters?!
