### ISSUE TITLE
Error occured when execute npm run webpack-dev

### ISSUE THREAD

**Issue by acantepie** [Limenius/symfony-react-sandbox#33]
Hello,
I am trying to run project on ubuntu but i have the following error :
(npm version:  5.0.3, node version: v8.0.0)

```
$ npm run webpack-serverside

> symfony-react-sandbox@1.0.0 webpack-serverside /home/acantepie/Workspace/symfony-react-sandbox
> encore dev --config webpack.config.serverside.js --watch

Running webpack ...


Webpack is watching the files…

 WARNING  Compiled with 3 warnings                                                                              20:33:58

 warning  in ./~/ajv/lib/async.js

96:20-33 Critical dependency: the request of a dependency is an expression

 warning  in ./~/ajv/lib/async.js

119:15-28 Critical dependency: the request of a dependency is an expression

 warning  in ./~/ajv/lib/compile/index.js

13:21-34 Critical dependency: the request of a dependency is an expression

    + 974 hidden modules
```

```
$ npm run webpack-dev

> symfony-react-sandbox@1.0.0 webpack-dev /home/acantepie/Workspace/symfony-react-sandbox
> webpack-dev-server --hot --inline --progress --colors --config webpack.config.js --port 8080 --output-public-path=http://localhost:8080/assets/build/

/home/acantepie/Workspace/symfony-react-sandbox/node_modules/@symfony/webpack-encore/index.js:11
    throw new Error('Are you trying to require index.js directly?');
    ^

Error: Are you trying to require index.js directly?
    at Object.<anonymous> (/home/acantepie/Workspace/symfony-react-sandbox/node_modules/@symfony/webpack-encore/index.js:11:11)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/acantepie/Workspace/symfony-react-sandbox/webpack.config.js:1:76)
    at Module._compile (module.js:569:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! symfony-react-sandbox@1.0.0 webpack-dev: `webpack-dev-server --hot --inline --progress --colors --config webpack.config.js --port 8080 --output-public-path=http://localhost:8080/assets/build/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the symfony-react-sandbox@1.0.0 webpack-dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/acantepie/.npm/_logs/2017-06-19T18_42_48_667Z-debug.log
```

and finally `An exception has been thrown during the rendering of a template ("Asset manifest file "/home/acantepie/Workspace/symfony-react-sandbox/web/build/manifest.json" does not exist.").` when i request http://127.0.0.1:8000/

Here my npm debug log : https://pastebin.com/uP3a4Ye7 .

Thanx for help,

**Comment by nacmartin** [comment]
Ooops, I was adapting this project to use webpack encore and forgot to change one line, to make the command `npm run webpack-dev` _actually_ use encore. I have just fixed it. it should work now, thanks for reporting this, @acantepie .

**Comment by acantepie** [comment]
Thx for help,
It solves the problem but i have an other error :
```
$ npm run webpack-serverside

> symfony-react-sandbox@1.0.0 webpack-serverside /home/acantepie/Workspace/symfony-react-sandbox
> encore dev --config webpack.config.serverside.js --watch

path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:1232:7)
    at find (/home/acantepie/Workspace/symfony-react-sandbox/node_modules/babel-loader/lib/resolve-rc.js:11:21)
    at module.exports (/home/acantepie/Workspace/symfony-react-sandbox/node_modules/@symfony/webpack-encore/lib/config/parse-runtime.js:64:47)
    at Object.<anonymous> (/home/acantepie/Workspace/symfony-react-sandbox/node_modules/@symfony/webpack-encore/bin/encore.js:18:23)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! symfony-react-sandbox@1.0.0 webpack-serverside: `encore dev --config webpack.config.serverside.js --watch`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the symfony-react-sandbox@1.0.0 webpack-serverside script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/acantepie/.npm/_logs/2017-06-20T16_53_34_022Z-debug.log
```

**Comment by nacmartin** [comment]
Now this error is very weird. I cannot reproduce it (just tried with a fresh clone), and this same command was working for you in the first message, and I didn't touch anything that can affect it in between your messages.

**Comment by acantepie** [comment]
I have reinstalled node module with yarn and it works. :) I have the error only when i use npm to install depdency.

But i have a 500 on website : 
`An exception has been thrown during the rendering of a template ("Notice: Undefined index: props")`
```
in app/Resources/views/recipe/home.html.twig (line 4)
{% extends 'base.html.twig' %}

{% block body %}
{{ react_component('RecipesApp', {'props': props}) }}
{% endblock %}
```

Error seems throw from "ReactRenderExtension.php" at line 90 when code trying to access to an undefined 'props' attribute : 
```
                     if ($this->shouldRenderServerSide($options)) {
            $serverSideStr = $this->renderer->render(
                $componentName,
                json_encode($data['props']),
                $domId,
                $this->registeredStores,
                $trace
            );
            $str .= $serverSideStr;
        }
```

Do you have the same error ?

**Comment by nacmartin** [comment]
Ah, just was checking. Sorry for this one. It seems like it was installing v0.13.0 of the bundle instead of v0.13.1, which fixes this
