### ISSUE TITLE
Cannot run SSR with the "external_server" mode

### ISSUE THREAD

**Issue by LoicGoyet** [Limenius/symfony-react-sandbox#53]
Hello,
I am tying to run the project with server side rendering with the "external_server" mode (I am running the `symfony3` branch).

So I modified the `mode` parameter from the `limenius_react` config to `"external_server"` and then I prompt the command `(cd ./app/Resources/node-server && node server)` to run the node server. But server don't start and throw this error :

```sh
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE node.sock
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at Server.setupListenHandle [as _listen2] (net.js:1334:19)
    at listenInCluster (net.js:1392:12)
    at Server.listen (net.js:1487:5)
    at Object.<anonymous> (/Users/loicgoyet/Workspace/test/symfony-react-sandbox/app/Resources/node-server/server.js:83:12)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
```
I don't know really well node so I tread carefully, but from what I understand, the `node.sock` file is missing. Is that on purpose ? Does it means we have to write some socket node.js to run the external_server mode ?

Thanks a lot for answering !

**Comment by LoicGoyet** [comment]
I found out a way to make it work ! You can checkout what I did on [this PR](https://github.com/Limenius/symfony-react-sandbox/pull/54)
